### ISSUE TITLE
Does not create a package.json

### ISSUE THREAD

**Issue by HansS** [frdmn/workspace-initiator#8]
Hans@HP-HANS C:\Users\Hans\Web\npm\packages\init-test

> init
> ? Name of your project? init-test
> ? Who maintains the project? HansS
> ? Do you want me to create a base README.md? Default
> ? Which license do you want to use? Apache 2.0
> ? Want me to initialize a git repository? No
> Success: Workspace successfully set up! Don't forget to adjust the mising placeholders :)

Hans@HP-HANS C:\Users\Hans\Web\npm\packages\init-test

> dir
>  Datenträger in Laufwerk C: ist Windows
>  Volumeseriennummer: 3AE6-A1D0

 Verzeichnis von C:\Users\Hans\Web\npm\packages\init-test

15.12.2015  17:27    <DIR>          .
15.12.2015  17:27    <DIR>          ..
15.12.2015  17:27               560 LICENSE
15.12.2015  17:27               722 README.md
               2 Datei(en),          1'282 Bytes
               2 Verzeichnis(se), 267'365'130'240 Bytes frei

**Comment by frdmn** [comment]
The creation of a `package.json` file is currently not a feature of init.js since I didn't want to limit it to Node projects.

**Comment by HansS** [comment]
Hi Jonas,thank's for the message

Date: Tue, 15 Dec 2015 11:50:26 -0800

**Comment by frdmn** [comment]
@HansS Very welcome :)
